public class Audiexample 
{
     public string CarModel;
     public string EngineType;
     public string Colour;
     public integer model;
     public void display()
     {
         system.debug('Model of the car :'+CarModel);
         system.debug('Type of  the Engine:'+EngineType);
         system.debug('Colour of the Car:'+colour);
         system.debug('Model of the Car:'+model);
         
     }
    
}